### ISSUE TITLE
[12.0] account_invoice_ubl: 21% VAT (NL) on product-item with EU customer (0% VAT)

### ISSUE THREAD

**Issue by mgielissen** [OCA/edi#107]
With a EU customer the VAT should be 0% but the UBL xml file shows 21% VAT (for NL) instead of 0% on the product item:

      <cac:ClassifiedTaxCategory>
        <cbc:ID schemeAgencyID="6" schemeID="UN/ECE 5305">S</cbc:ID>
        <cbc:Name>BTW(VAT) 21%</cbc:Name>
        <cbc:Percent>21.0</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID schemeAgencyID="6" schemeID="UN/ECE 5153">VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:ClassifiedTaxCategory>

**Comment by alexis-via** [comment]
Be sure not to mix 2 things: the Tax classification of the product (21% in your case), and the tax that applies on the invoice line due to the particular fiscal position (0% in your case). Both information are present in the XML.
Otherwise, I mis-understood the UBL standard and you should re-open this issue.
