### ISSUE TITLE
ModuleNotFoundError: No module named 'factur-x'

### ISSUE THREAD

**Issue by simahawk** [OCA/edi#260]
Just tracking the issue. At least on v13.

**Comment by etobella** [comment]
@alexis-via After checking, there are two issues:

- factur-x was not added on the requirements.txt
- the module account_e-invoice_generate cannot be installed as it excludes the account_facturx, that is autoinstalled and, forcefully installed on the module

So, Right now, Travis is not working due to this... 
I will make a PR that modifies travis and does not check this module, but it is probably needed to fix the issue.

**Comment by etobella** [comment]
The problem comes from #208 and as explained there, it affects a lot of modules

**Comment by alexis-via** [comment]
Thanks for the investigation. I need to figure out how you access the appropriate runbot logs to understand the issue...
