### ISSUE TITLE
[12.0]Print Factur-X invoice for the Kosovo 

### ISSUE THREAD

**Issue by flotho** [OCA/edi#475]
**Is your feature request related to a problem?**
I'm trying to invoice a customer in Kosovo.
The country is not tagged in the eu
![image](https://user-images.githubusercontent.com/1043935/140066209-b055402d-ab3f-4f78-a31c-63d3b789dbf7.png)

Printing the invoice for this customer causes this pbm :

![image](https://user-images.githubusercontent.com/1043935/140066370-758b5014-ceaf-4b27-bb8c-c8a9b87cd308.png)

**Describe the solution you'd like**

be able to print for country that are not in the country list, be able to add country in this list

**Describe alternatives you've considered**

be able to print for country that are not in the country list

**Comment by flotho** [comment]
ping @alexis-via , any advice or workaround for this one ?

**Comment by flotho** [comment]
Maybe adding a field in https://github.com/OCA/edi/blob/12.0/account_invoice_facturx/views/res_partner.xml to check if we print factur x for a specific customer or maybe on the country could do the trick.

Regards

**Comment by alexis-via** [comment]
I understand the Kosovo is not recognized by all the countries as an independant country and that XK is not an official ISO country code, cf https://en.wikipedia.org/wiki/ISO_3166-1. It's probably the reason why XK is not in the list of allowed ISO country codes of the factur-X XSD. Your problem is the Factur-X XSD, not Odoo. You may want to disable the Factur-X XSD check in the code: for that, just comment this block of code: https://github.com/OCA/edi/blob/12.0/account_invoice_facturx/models/account_invoice.py#L743
